prSections:
  - title: open
    filters: is:open
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
  prsLimit: 20
  prApproveComment: LGTM!
  issuesLimit: 5
  view: prs
  refetchIntervalMinutes: 30
keybindings:
  prs:
    - key: d
      command: |-
        gh pr checkout {{.PrNumber}} &&
          nvim -c ":DiffviewOpen origin/$(gh pr status --json baseRefName -q '.currentBranch.baseRefName')...{{.HeadRefName}}"
    - key: C
      command: |-
        gh pr checkout {{.PrNumber}} &&
          nvim -c ":Octo pr edit {{.PrNumber}}"
repoPaths: { kkhs/*: ~/ghq/github.com/kkhs/* }
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: ""
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
